### ISSUE TITLE
Metro: Investigate bundle size optimisations

### ISSUE THREAD

**Issue by tido64** [microsoft/rnx-kit#111]
Haul currently produces smaller bundles than Metro. We need to investigate how we can narrow the gap.

Leads to explore:
- [ ] [Haul's Babel preset](https://github.com/callstack/haul/blob/master/packages/haul-babel-preset-react-native/src/index.ts) is smaller than [Metro's](https://github.com/facebook/metro/blob/master/packages/metro-react-native-babel-preset/src/configs/main.js)
- [ ] Tree shaking (see #127)

Issues:
- [x] Allow options to be forwarded to `metro-react-native-babel-preset` (#136)
- [ ] Enabling `experimentalImportSupport` can help reduce the bundle size but must be done correctly (#142)
