### ISSUE TITLE
Enable pnpm mode to catch issues earlier

### ISSUE THREAD

**Issue by tido64** [microsoft/rnx-kit#2783]
Despite our best efforts, we cannot catch all pnpm related issues before they hit users. We need to be more proactive and catch them earlier. This means that we _need_ to enable pnpm mode.

To enable pnpm mode:

```diff
diff --git a/.yarnrc.yml b/.yarnrc.yml
index f59a253e..b2cfdf1f 100644
--- a/.yarnrc.yml
+++ b/.yarnrc.yml
@@ -7,7 +7,7 @@ logFilters:
     level: discard
   - code: YN0013 # X can't be found in the cache and will be fetched from the remote registry
     level: discard
-nodeLinker: node-modules
+nodeLinker: pnpm
 npmRegistryServer: "https://registry.npmjs.org"
 packageExtensions:
   "@fluentui/utilities@*":
```

### Work items

- [x] https://github.com/microsoft/rnx-kit/pull/2778
- [x] https://github.com/microsoft/rnx-kit/pull/2779
- [x] https://github.com/microsoft/rnx-kit/pull/2780
- [x] https://github.com/microsoft/rnx-kit/pull/2781
- [x] https://github.com/microsoft/rnx-kit/pull/2782
- [x] https://github.com/microsoft/rnx-kit/pull/2784
- [x] https://github.com/microsoft/rnx-kit/pull/2787
- [x] https://github.com/microsoft/rnx-kit/pull/2791
- [x] https://github.com/microsoft/rnx-kit/pull/2792
- [x] https://github.com/microsoft/rnx-kit/pull/2793
- [x] https://github.com/microsoft/rnx-kit/pull/2794
- [x] https://github.com/microsoft/rnx-kit/pull/2795
- [x] https://github.com/microsoft/rnx-kit/pull/2797
- [x] https://github.com/microsoft/rnx-kit/pull/2798
- [x] https://github.com/microsoft/rnx-kit/pull/2799
- [x] https://github.com/microsoft/rnx-kit/pull/2800
- [x] https://github.com/microsoft/rnx-kit/pull/2806
- [x] https://github.com/microsoft/rnx-kit/pull/2808
- [x] https://github.com/microsoft/rnx-kit/pull/2809

### Upstream fixes

- [x] https://github.com/facebook/react-native/pull/41398
  - [ ] 0.73: https://github.com/facebook/react-native/pull/41444
  - [ ] 0.72: https://github.com/facebook/react-native/pull/41445
  - [ ] macos 0.73:https://github.com/microsoft/react-native-macos/pull/1982
  - [ ] macos 0.72: https://github.com/microsoft/react-native-macos/pull/1981
- [x] https://github.com/facebook/react-native/pull/41399
  - [ ] 0.73: https://github.com/facebook/react-native/pull/41457
  - [ ] 0.72: https://github.com/facebook/react-native/pull/41456
  - [ ] macos 0.73: https://github.com/microsoft/react-native-macos/pull/1984
  - [ ] macos 0.72: https://github.com/microsoft/react-native-macos/pull/1983
